### ISSUE TITLE
an alternative solution based on nginx content cache

### ISSUE THREAD

**Issue by link89** [richardklose/github-release-mirror#1]
Hi @richardklose , I have another solution for this just in case someone else needs it.
It is based on [nginx content cache](https://docs.nginx.com/nginx/admin-guide/content-cache/content-caching/). Here is the configuration snippet.

```
// in http block
    proxy_cache_path /var/log/_cache_ keys_zone=npmbinary:10m;

// in server block
        location /_dist_/ {
                proxy_cache npmbinary;
                proxy_cache_key $uri$is_args$args;
                proxy_pass https://cdn.npm.taobao.org/dist/;
                proxy_cache_valid 200 10000h;
                proxy_cache_methods GET;
        }
```

And you can make use of the cache this way (take electron as an example)
```
ELECTRON_MIRROR=http://example.com/_dist_/electron/ npm install electron 
```

**Comment by richardklose** [comment]
Thanks for the alternative. As this not a real issue regarding the actual project or it's code, I'll close this.

As far as I understand your suggestion, this requires, that the files have actively downloaded once through the nginx proxy. This wouldn't be a solution for the use case I had, on which I have built this project. What I wanted, was a mirror, that downloads every artifact to our company's mirror of every release of a GitHub project, even if it isn't actively used by any of our company's projects. If I understand your solution correctly, it would only cache files, that have been actively downloaded once (e.g. by a npm install).
Or in short: using nginx content cache here, is really just a cache, not a full mirror. A cron job for calling the GitHub API and downloading files would still be required and this is the main point of this project.
